version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    external:
      name: app-network
    driver: bridge

